//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdressSearch.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdressSearch.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam
        ///Adrian
        ///Adolf
        ///Alan
        ///Albert
        ///Aleksander
        ///Aleksy
        ///Alfred
        ///Alojzy
        ///Ambrozy
        ///Andrzej
        ///Antoni
        ///Anzelm
        ///Apolinary
        ///Aureliusz
        ///Arkadiusz
        ///Artur
        ///Augustyn
        ///Bartek
        ///Bartosz
        ///Bartlomiej
        ///Bogdan
        ///Boguslaw
        ///Boleslaw
        ///Borys
        ///Cezary
        ///Cyprian
        ///Czeslaw
        ///Damian
        ///Daniel
        ///Dariusz
        ///Dawid
        ///Dionizy
        ///Dominik
        ///Edward
        ///Emil
        ///Erwin
        ///Ernest
        ///Eryk
        ///Fabian
        ///Feliks
        ///Filip
        ///Franciszek
        ///Fryderyk
        ///Gabriel
        ///Grzegorz
        ///Henryk
        ///Herbert
        ///Ignacy
        ///Ireneusz
        ///Igor
        ///Jacek
        ///Janusz
        ///Jakub
        ///Jan
        ///Jarek
        ///Jaroslaw
        ///Jerzy
        ///Juliusz
        ///Jozef
        ///Kajetan
        ///K [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PolishNames {
            get {
                return ResourceManager.GetString("PolishNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowak
        ///Kowalski
        ///Wisniewski
        ///Dabrowski
        ///Lewandowski
        ///Wojcik
        ///Kaminski
        ///Kowalczyk
        ///Zielinski
        ///Szymanski
        ///Wozniak
        ///Kozlowski
        ///Jankowski
        ///Wojciechowski
        ///Kwiatkowski
        ///Kaczmarek
        ///Mazur
        ///Krawczyk
        ///Piotrowski
        ///Grabowski
        ///Nowakowski
        ///Pawlowski
        ///Michalski
        ///Nowicki
        ///Adamczyk
        ///Dudek
        ///Zajac
        ///Wieczorek
        ///Jablonski
        ///Krol
        ///Majewski
        ///Olszewski
        ///Jaworski
        ///Wrobel
        ///Malinowski
        ///Pawlak
        ///Witkowski
        ///Walczak
        ///Stepien
        ///Gorski
        ///Rutkowski
        ///Michalak
        ///Sikora
        ///Ostrowski
        ///Baran
        ///Duda
        ///Szewczyk
        ///Tomaszewski
        ///Pietrzak
        ///Marciniak
        ///Wroblewski [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TypicalPolishSurnames {
            get {
                return ResourceManager.GetString("TypicalPolishSurnames", resourceCulture);
            }
        }
    }
}
