//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCApp.Translate.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string AccountHello {
            get {
                return ResourceManager.GetString("AccountHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string AccountInvalidPassword {
            get {
                return ResourceManager.GetString("AccountInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string AccountLogIn {
            get {
                return ResourceManager.GetString("AccountLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string AccountLogOff {
            get {
                return ResourceManager.GetString("AccountLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First post code.
        /// </summary>
        public static string DistrictFirstPostCode {
            get {
                return ResourceManager.GetString("DistrictFirstPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last post code.
        /// </summary>
        public static string DistrictLastPostCode {
            get {
                return ResourceManager.GetString("DistrictLastPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string DistrictNumber {
            get {
                return ResourceManager.GetString("DistrictNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string DistrictPostCode {
            get {
                return ResourceManager.GetString("DistrictPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last search results.
        /// </summary>
        public static string LastSearchResults {
            get {
                return ResourceManager.GetString("LastSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage districts.
        /// </summary>
        public static string MenuManageDistricts {
            get {
                return ResourceManager.GetString("MenuManageDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My districts.
        /// </summary>
        public static string MenuMyDistricts {
            get {
                return ResourceManager.GetString("MenuMyDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PersonAddress {
            get {
                return ResourceManager.GetString("PersonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PersonSelected {
            get {
                return ResourceManager.GetString("PersonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PersonSurname {
            get {
                return ResourceManager.GetString("PersonSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        public static string PersonTelephoneNum {
            get {
                return ResourceManager.GetString("PersonTelephoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses found: {0}.
        /// </summary>
        public static string SearchAddressesCount {
            get {
                return ResourceManager.GetString("SearchAddressesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. This can take couple of minutes....
        /// </summary>
        public static string SearchAddressWait {
            get {
                return ResourceManager.GetString("SearchAddressWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search adresses.
        /// </summary>
        public static string SearchAdresses {
            get {
                return ResourceManager.GetString("SearchAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display adresses of selected people.
        /// </summary>
        public static string SearchDisplaySelected {
            get {
                return ResourceManager.GetString("SearchDisplaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show map.
        /// </summary>
        public static string SearchDisplaySelectedOnMap {
            get {
                return ResourceManager.GetString("SearchDisplaySelectedOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run search from Krak.dk.
        /// </summary>
        public static string SearchRunOnKrak {
            get {
                return ResourceManager.GetString("SearchRunOnKrak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        public static string SearchSaveSelectedAsPdf {
            get {
                return ResourceManager.GetString("SearchSaveSelectedAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected adresses.
        /// </summary>
        public static string SearchSelectedAdresses {
            get {
                return ResourceManager.GetString("SearchSelectedAdresses", resourceCulture);
            }
        }
    }
}
