//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCApp.Translate.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string AccountHello {
            get {
                return ResourceManager.GetString("AccountHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string AccountInvalidPassword {
            get {
                return ResourceManager.GetString("AccountInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string AccountLogIn {
            get {
                return ResourceManager.GetString("AccountLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string AccountLogOff {
            get {
                return ResourceManager.GetString("AccountLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string AddPerson {
            get {
                return ResourceManager.GetString("AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route with number.
        /// </summary>
        public static string AutocompleteAddressEnterLocation {
            get {
                return ResourceManager.GetString("AutocompleteAddressEnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1tv, basement, etc.
        /// </summary>
        public static string AutocompleteAddressEnterLocationDetails {
            get {
                return ResourceManager.GetString("AutocompleteAddressEnterLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CongregationName {
            get {
                return ResourceManager.GetString("CongregationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District adresses.
        /// </summary>
        public static string DistrictAddresses {
            get {
                return ResourceManager.GetString("DistrictAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary .kml file.
        /// </summary>
        public static string DistrictBoundaryKml {
            get {
                return ResourceManager.GetString("DistrictBoundaryKml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete district.
        /// </summary>
        public static string DistrictDelete {
            get {
                return ResourceManager.GetString("DistrictDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit district.
        /// </summary>
        public static string DistrictEdit {
            get {
                return ResourceManager.GetString("DistrictEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First post code.
        /// </summary>
        public static string DistrictFirstPostCode {
            get {
                return ResourceManager.GetString("DistrictFirstPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last post code.
        /// </summary>
        public static string DistrictLastPostCode {
            get {
                return ResourceManager.GetString("DistrictLastPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string DistrictNumber {
            get {
                return ResourceManager.GetString("DistrictNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string DistrictPostCode {
            get {
                return ResourceManager.GetString("DistrictPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to report completion of {0} district?.
        /// </summary>
        public static string DistrictReportCompleteConfirm {
            get {
                return ResourceManager.GetString("DistrictReportCompleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for reporting district completion!.
        /// </summary>
        public static string DistrictReportCompleteThanks {
            get {
                return ResourceManager.GetString("DistrictReportCompleteThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date given.
        /// </summary>
        public static string DistrictReportInvalidDate {
            get {
                return ResourceManager.GetString("DistrictReportInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report type.
        /// </summary>
        public static string DistrictReportType {
            get {
                return ResourceManager.GetString("DistrictReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string DistrictReportTypes_Complete {
            get {
                return ResourceManager.GetString("DistrictReportTypes_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string DistrictReportTypes_Request {
            get {
                return ResourceManager.GetString("DistrictReportTypes_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string DistrictReportTypes_Return {
            get {
                return ResourceManager.GetString("DistrictReportTypes_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string DistrictSearchPhrase {
            get {
                return ResourceManager.GetString("DistrictSearchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last search results.
        /// </summary>
        public static string LastSearchResults {
            get {
                return ResourceManager.GetString("LastSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregations.
        /// </summary>
        public static string MenuCongregations {
            get {
                return ResourceManager.GetString("MenuCongregations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free districts.
        /// </summary>
        public static string MenuFreeDistricts {
            get {
                return ResourceManager.GetString("MenuFreeDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage districts.
        /// </summary>
        public static string MenuManageDistricts {
            get {
                return ResourceManager.GetString("MenuManageDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My districts.
        /// </summary>
        public static string MenuMyDistricts {
            get {
                return ResourceManager.GetString("MenuMyDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reports.
        /// </summary>
        public static string MenuPendingReports {
            get {
                return ResourceManager.GetString("MenuPendingReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string PagedListLinkToNextPageFormat {
            get {
                return ResourceManager.GetString("PagedListLinkToNextPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string PagetListPageCountAndCurrentLocationFormat {
            get {
                return ResourceManager.GetString("PagetListPageCountAndCurrentLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find location. Please retype address..
        /// </summary>
        public static string PersonAddCannotFindLocation {
            get {
                return ResourceManager.GetString("PersonAddCannotFindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide street name.
        /// </summary>
        public static string PersonAddProvideStreet {
            get {
                return ResourceManager.GetString("PersonAddProvideStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide street number.
        /// </summary>
        public static string PersonAddProvideStreetNumber {
            get {
                return ResourceManager.GetString("PersonAddProvideStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PersonAddress {
            get {
                return ResourceManager.GetString("PersonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New address added!.
        /// </summary>
        public static string PersonAddSuccess {
            get {
                return ResourceManager.GetString("PersonAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0} {1}, {2}?.
        /// </summary>
        public static string PersonDeleteConfirmation {
            get {
                return ResourceManager.GetString("PersonDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add\Delete addresses.
        /// </summary>
        public static string PersonEditButton {
            get {
                return ResourceManager.GetString("PersonEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addresses. Run {0} or add adresses manually..
        /// </summary>
        public static string PersonListEmpty {
            get {
                return ResourceManager.GetString("PersonListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search engine.
        /// </summary>
        public static string PersonListEmptySearchEngineLink {
            get {
                return ResourceManager.GetString("PersonListEmptySearchEngineLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; surname.
        /// </summary>
        public static string PersonNameSurname {
            get {
                return ResourceManager.GetString("PersonNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PersonRemarks {
            get {
                return ResourceManager.GetString("PersonRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PersonSelected {
            get {
                return ResourceManager.GetString("PersonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PersonSurname {
            get {
                return ResourceManager.GetString("PersonSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        public static string PersonTelephoneNum {
            get {
                return ResourceManager.GetString("PersonTelephoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report district completed.
        /// </summary>
        public static string ReportDistrictCompletion {
            get {
                return ResourceManager.GetString("ReportDistrictCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is complete.
        /// </summary>
        public static string SearchAddressComplete {
            get {
                return ResourceManager.GetString("SearchAddressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses found: {0}.
        /// </summary>
        public static string SearchAddressesCount {
            get {
                return ResourceManager.GetString("SearchAddressesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New search results.
        /// </summary>
        public static string SearchAddressesNew {
            get {
                return ResourceManager.GetString("SearchAddressesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous search results.
        /// </summary>
        public static string SearchAddressesPrevious {
            get {
                return ResourceManager.GetString("SearchAddressesPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses found in previous search: {0}.
        /// </summary>
        public static string SearchAddressesPreviousCount {
            get {
                return ResourceManager.GetString("SearchAddressesPreviousCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading list of previously found adresses....
        /// </summary>
        public static string SearchAddressLoadingOldAdresses {
            get {
                return ResourceManager.GetString("SearchAddressLoadingOldAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address map.
        /// </summary>
        public static string SearchAddressMap {
            get {
                return ResourceManager.GetString("SearchAddressMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving found adresses..
        /// </summary>
        public static string SearchAddressSave {
            get {
                return ResourceManager.GetString("SearchAddressSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. This can take couple of minutes....
        /// </summary>
        public static string SearchAddressWait {
            get {
                return ResourceManager.GetString("SearchAddressWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search progress: {0}%.
        /// </summary>
        public static string SearchAddressWaitProgress {
            get {
                return ResourceManager.GetString("SearchAddressWaitProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search complete. Select Poles on below list..
        /// </summary>
        public static string SearchAdressComplete {
            get {
                return ResourceManager.GetString("SearchAdressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to search for new adresses? Note: It will clear all previous selects..
        /// </summary>
        public static string SearchAdressConfirm {
            get {
                return ResourceManager.GetString("SearchAdressConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search adresses.
        /// </summary>
        public static string SearchAdresses {
            get {
                return ResourceManager.GetString("SearchAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while search: {0}.
        /// </summary>
        public static string SearchAdressesError {
            get {
                return ResourceManager.GetString("SearchAdressesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new people have been found during search. .
        /// </summary>
        public static string SearchAdressNoPerson {
            get {
                return ResourceManager.GetString("SearchAdressNoPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show map.
        /// </summary>
        public static string SearchDisplaySelectedOnMap {
            get {
                return ResourceManager.GetString("SearchDisplaySelectedOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run search adresses again.
        /// </summary>
        public static string SearchRunOnKrak {
            get {
                return ResourceManager.GetString("SearchRunOnKrak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Word.
        /// </summary>
        public static string SearchSaveSelectedAsDoc {
            get {
                return ResourceManager.GetString("SearchSaveSelectedAsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        public static string SearchSaveSelectedAsPdf {
            get {
                return ResourceManager.GetString("SearchSaveSelectedAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected adresses.
        /// </summary>
        public static string SearchSelectedAdresses {
            get {
                return ResourceManager.GetString("SearchSelectedAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable address sharing.
        /// </summary>
        public static string SharingEnabled {
            get {
                return ResourceManager.GetString("SharingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured :(.
        /// </summary>
        public static string UnexpectedErrorOccured {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete admin user.
        /// </summary>
        public static string UserDeleteAdmin {
            get {
                return ResourceManager.GetString("UserDeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete user {0}?.
        /// </summary>
        public static string UserDeleteConfirmation {
            get {
                return ResourceManager.GetString("UserDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deletion is impossible because he has districts assigned..
        /// </summary>
        public static string UserDeleteDistrictsAssigned {
            get {
                return ResourceManager.GetString("UserDeleteDistrictsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My districts.
        /// </summary>
        public static string WebPageTitle {
            get {
                return ResourceManager.GetString("WebPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your completions.
        /// </summary>
        public static string YourCompletions {
            get {
                return ResourceManager.GetString("YourCompletions", resourceCulture);
            }
        }
    }
}
